config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'start_page#index'
  resources :products do
    resources :variants
  end

  resources :receipts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
 # validates :name, presence: true
  belongs_to :receipt, inverse_of: :items
  belongs_to :variants
end

app/models/product.rb
class Product < ApplicationRecord
  validates :name, :description, presence: true
  has_many :variants, inverse_of: :product
    accepts_nested_attributes_for :variants, allow_destroy: true
end

app/models/receipt.rb
class Receipt < ApplicationRecord
  validates :name, presence: true
  has_many :items, inverse_of: :receipt
  has_many :variants, through: :items, inverse_of: :receipt
  accepts_nested_attributes_for :items
end

app/models/variant.rb
class Variant < ApplicationRecord
  validates :name, presence: true
  belongs_to :product, inverse_of: :variants
  # has_many :items, inverse_of: :variant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
    @product.variants.build
  end

  def create
    @product = Product.create(product_params)
     if @product.valid?
      redirect_to products_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @product = Product.find(params[:id])
    @variants = @product.variants.all
  end

  def destroy
     @product = Product.find(params[:id])
     @product.destroy
     redirect_to products_path
  end


  private

  def product_params
    params.require(:product).permit(:name, :description, variants_attributes: [:id, :name])
  end

end

app/controllers/receipts_controller.rb
 class ReceiptsController < ApplicationController

  def index
    @receipts = Receipt.all
  end

  def new
    @receipt = Receipt.new
    @receipt.items.build
  end

  def create
    @receipt = Receipt.create(receipt_params)
    if @receipt.valid?
      redirect_to receipts_path
    else
     render :new, status: :unprocessable_entity
    end
  end
  

  private

  def receipt_params
    params.require(:receipt).permit(:name, items_attributes: [:id, :variant_id])
  end

end

app/controllers/start_page_controller.rb
class StartPageController < ApplicationController

  def index
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
end

app/helpers/start_page_helper.rb
module StartPageHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Products</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb

<div class="container">
  <h2> Přehled Produktů </h2>
    <% if @products %>
      <% @products.each do |product| %>
        <p class="product-name">
          <%= link_to product.name, product_path(product) %>
        </p>
        <p>
         <%= product.description %>
        </p>
      <% end %>
    <% end %>

  <%= link_to 'Nový produkt', new_product_path, class: 'btn btn-primary' %>

  </div>

app/views/products/new.html.erb
<div class="container">
  <h2> Vložte nový produkt </h2>
  <%= simple_form_for @product do |f| %>

    <div class="name">
      <%= f.input :name, label:'Název Produktu' %>     
    </div>

    <br/>

    <div class="description">
      <%= f.input :description, label: 'Popis' %>
    </div>

    <br/>

    <%= f.simple_fields_for :variants do |builder| %>

      <%= builder.input :name, label: 'Varianta produktu:'%>
      <%= builder.check_box :_destroy %>
      <%= builder.label :_destroy, "Odstranit"%>

    <% end %>

    <br/>

    <button type"button" id="add-variant" class="pull-right btn btn-primary">Přidat variantu</button>

    <br/><br/>

    <div class="form-actions">
      <%= f.button :submit, 'Uložit produkt', class:"btn btn-primary"%>
    </div>

<% end %>
</div>

app/views/products/show.html.erb

<div class="container">
<%= @product.name %>
<% @variants.each do |variant| %>
  <p>
  <%= variant.name %>
  </p>
<% end %>
<%= link_to 'Smazat produkt', product_path(@product), method: :delete, data: {confirm: "Nevratně smazat produkt?"}, class:"btn btn-danger" %>
</div>

app/views/receipts/index.html.erb
<h2> Přehled dokladů </h2>
  <% if @receipts %>
    <% @receipts.each do |receipt| %>
      <p>
      <%= link_to receipt.name, receipt_path(receipt) %>
      </p>
    <% end %>
  <% end %>

  <%= link_to 'Nový doklad', new_receipt_path, class: 'btn btn-primary' %>

app/views/receipts/new.html.erb
<div class="container">
  <h2> Nový doklad: </h2>

  <%= simple_form_for @receipt do |f| %>
    <div class="form-inputs">
      <%= f.input :name, label: 'Receipt Number' %>
    </div>
    <div class="form-inputs">
      <%= f.simple_fields_for :items do |builder| %>
      <%= builder.collection_select :variant_id, Variant.all, :id, :name, {prompt: 'Choose a Variant'} %>
      <% end %>
    </div>
    <br />
    <div class="form-actions">
      <%= f.button :submit, 'Save Receipt', class:"btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/start_page/index.html.erb
<h1>Přehled</h1>
<h2>Vyberte z následujících položek</h2>
<p>
  <ul>
    <li><%= link_to 'Produkty', products_path %></li>
    <li><%= link_to 'Doklady', receipts_path %></li>
  </ul> 